name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jre: [17]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        include:
          - jre: 21
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mustache Specs
        run: |
          git submodule update --init --recursive
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jre }}
          distribution: 'temurin'
      - name: Install
        run: mvn clean install -DskipTests --batch-mode --no-transfer-progress
      - name: Build
        run: mvn clean package --batch-mode --no-transfer-progress
